### ISSUE TITLE
jotai is a good choose for react concurrent mode？

### ISSUE THREAD

**Issue by qinjialei24** [dai-shi/will-this-react-global-state-work-in-concurrent-rendering#45] opened 2021-08-18 08:05 UTC
Good Job！But i have some questions

I  see this issue
![image](https://user-images.githubusercontent.com/25007230/129860957-07990bae-5b36-44bf-b61b-7978a15e4249.png)

As you can see from above，jotai is not good enough for react concurrent mode，So would you have plans to make this（CM） better ？

**Comment by dai-shi** [comment] 2021-08-18 08:53
Concurrent React is not finalized and it's basically predicting the future.
That said, it's still something we believe is better or friendly for concurrent react.
We would like to make it better, but at this point it's the best we could do.

Please refer: https://github.com/reactwg/react-18/discussions/70
We are still at level 1, but can go to level 2 instantly once React releases `useMutableSource`.
Our hope is to reach level 3, eventually.

> Another example is to use a mutable store with immutable snapshots which do not change during render, but this strategy is still under research.

It's still under research. react-tracked can probably fulfill "with immutable snapshots which do not change during render". jotai does not do at this moment, but would add some restriction or convention in the api to follow this. zustand and valtio will never do this by design.

Please note that as app developers it's not super important to follow this. This is just one aspect of following new react features to get some benefits, but they might not fit with all apps requirements.

**Comment by dai-shi** [comment] 2021-12-24 14:06
Closing, but feel free to continue discussion.

**Closed by dai-shi** 2021-12-24 14:06 UTC
